name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # 构建、部署主应用
  build-root:
    runs-on: ubuntu-latest
    
    # 步骤
    steps:
    # 拉取代码
    - uses: actions/checkout@v3
      with:
        submodules: true

    # 设置 node 环境
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    # 构建
    - name: Build
      run: |
        # 进入主应用目录
        cd single-spa-root-template
        # 安装 node modules
        npm install
        # 打包
        npm run build
        # 压缩
        zip -r dist.zip dist/
    
    # 上传静态资源
    - name: Upload
      uses: easingthemes/ssh-deploy@master
      env:
          SSH_PRIVATE_KEY: ${{ env.KEY }}
          ARGS: '-avz --delete'
          SOURCE: './dist.zip'
          REMOTE_HOST: ${{ env.HOST }}
          REMOTE_USER: ${{ env.USERNAME }}
          TARGET: /root/static # 服务器目标路径

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami

        
