name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # 构建、部署主应用
  build-root:
    runs-on: ubuntu-latest
    
    # 步骤
    steps:
    # 拉取代码
    - uses: actions/checkout@v3
      with:
        submodules: true

    # 设置 node 环境
    - name: Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    # 构建
    - name: Build
      run: |
        cd single-spa-root-template # 进入主应用目录
        npm install # 安装 node modules
        npm run build # 打包
        cd dist # 进入静态资源目录
        rm -f dist.zip # 删除之前存在的压缩文件
        zip -r dist.zip * # 压缩
    
    # 上传静态资源
    - name: Upload
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KEY }}
        ARGS: '-rltgoDzvO --delete'
        SOURCE: 'single-spa-root-template/dist/dist.zip'
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: /root/single_spa

    # 解压静态资源
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/single_spa
          unzip dist.zip
          

        
