name: Deploy

# 触发条件
on:
  workflow_dispatch: # 手动触发
  push: # master/test/dev 分支更新时触发
    branches: [ 'master', 'test', 'dev' ]

jobs:
  # 复用工作流 - 构建并部署主应用
  deploy-root:
    uses: ./.github/workflows/reusable.yaml
    with:
      APP_NAME: single-spa-root-template
      STATIC_PATH: /root/single_spa
      DIST_NAME: dist-root-${{ github.run_number }}.tar
    secrets: inherit

  # 复用工作流 - 构建并部署子应用
  deploy-app1:
    uses: ./.github/workflows/reusable.yaml
    with:
      APP_NAME: single-spa-app-vue3-vite-template
      STATIC_PATH: /root/single_spa/static/single-spa-app-vue3-vite-template
      DIST_NAME: dist-app1-${{ github.run_number }}.tar
    secrets: inherit

  # 复用工作流 - 构建并部署子应用
  deploy-app2:
    uses: ./.github/workflows/reusable.yaml
    with:
      APP_NAME: single-spa-app-vue3-webpack5-template
      STATIC_PATH: /root/single_spa/static/single-spa-app-vue3-webpack5-template
      DIST_NAME: dist-app2-${{ github.run_number }}.tar
    secrets: inherit
