name: NodeJS with Webpack

# 触发条件
on:
  workflow_dispatch: # 手动触发
  push: # master/test/dev 分支更新时触发
    branches: [ 'master', 'test', 'dev' ]

# 环境变量
env:
  ROOT_STATIC_PATH: /root/single_spa # 部署服务器，主应用资源路径
  ROOT_PATH: single-spa-root-template # Github Actions 主应用代码路径
  APP1_STATIC_PATH: /root/single_spa/static/single-spa-app-vue3-vite-template # 部署服务器，子应用1资源路径
  APP1_PATH: single-spa-app-vue3-vite-template # Github Actions 子应用1代码路径
  APP2_STATIC_PATH: /root/single_spa/static/single-spa-app-vue3-webpack5-template # 部署服务器，子应用2资源路径
  APP2_PATH: single-spa-app-vue3-webpack5-template # Github Actions 子应用2代码路径

jobs:
  # 克隆代码仓库
  checkout-git:
    runs-on: ubuntu-latest
    
    # 步骤
    steps:
    # 拉取代码
    - uses: actions/checkout@v3
      with:
        submodules: true

  # 复用工作流 - 构建并部署主应用
  deploy-root-app:
    needs: checkout-git
    uses: ./.github/workflows/reusable.yaml
    with:
      APP_NAME: single-spa-root-template
      ROOT_STATIC_PATH: /root/single_spa
      DIST_NAME: dist-root-app-${{ github.run_number }}.tar
